### ISSUE TITLE
Can't start second instance for testing

### ISSUE THREAD

**Issue by tommis** [sireliah/dragit#19] opened 2022-05-04 22:05 UTC
On readme it states that it's possible to start two instances for testing purposes but when I try this on my machine I get the following.

```[2022-05-04T22:00:43Z INFO  dragit::dnd] Starting com.sireliah.Dragit
[2022-05-04T22:00:43Z INFO  dragit::p2p] I am Peer: PeerId("12D3KooWAXeuYiZ1e2dPsk1KQnRZqdCEB2QjKuTqxhqfDYmW3PdT")
[2022-05-04T22:00:43Z ERROR dragit::dnd] Server error: Other(Custom { kind: Other, error: Other(A(A(Os { code: 98, kind: AddrInUse, message: "Address already in use" }))) })

(dragit:138943): Gtk-WARNING **: 01:00:43.106: Locale not supported by C library.
        Using the fallback 'C' locale.
```

First instance starts without problems.

**Comment by sireliah** [comment] 2022-05-06 18:23
Yes, that's an issue that was caused by binding a port to a fixed value (`~/.config/dragit/config.toml` by default on Linux, if you're using Windows, this config will be in different place). This means that two instances are trying to listen on the same port.

I'll to fix it, however before that I can offer you following, a bit hakish, solution:

1. Set `~/.config/dragit/config.toml` port value to 0, which will cause the application to pick a random port
2. Run one instance of dragit (cargo run)
3. Edit the [src/dnd/mod.rs](https://github.com/sireliah/dragit/blob/master/src/dnd/mod.rs#L207) and change the application name to something else, for example "com.sireliah.Dragit2"
4. Run another instance of dragit
5. Profit

The step 3. is required, because Gtk applications cannot share the same name.

A bit less clumsy solution would be to use environment variable to preventing the recompilation of the application. But please try the steps above and tell if this worked!

**Comment by sireliah** [comment] 2022-05-14 15:27
I'm closing this ticket, since it's now possible to test the app behaviour on a single machine. Please check the [README](https://github.com/sireliah/dragit/blob/master/README.md#starting-two-instance-on-the-same-machine)!

**Closed by sireliah** 2022-05-14 15:27 UTC
